### ISSUE TITLE
YoloAI Bot

### ISSUE THREAD

**Issue by GamebP** [KetamineAddict/freedom#3]
[YoloAI](https://www.v7labs.com/blog/yolo-object-detection) is an `Object Detection` artificial intelligence.  
This could be used in Osu! itself.. But what I herd from a different user who made it - it took them about 6months to make it work and press z x keys.  
## 
This could apply in your private program if you accept this to be implemented in your code.
Plus it takes alot of time and patiance. Could be used in doing real High PP plays if so.

**Comment by KetamineAddict** [comment]
The problem is that it will never perform as human as a code that is set in stone with my own preferred humanization methods i think.

Also this is not the goal of my journey here. I dont wanna code on an ai or something but rather my first cheat features. Im just not interested in ai.

**Comment by GamebP** [comment]
Alright
